'use client'

import Link from 'next/link'
import { type FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from 'react'
import { adminFetch } from '@/lib/admin-fetch'
import { FORMAS_CAIXA, type FormaCaixa, type ResumoCaixa } from '@/lib/calculos-caixa'

type Sessao = { id:number; status:string; saldo_inicial_dinheiro:number|string; aberto_por_nome:string; aberto_em:string; fechado_por_nome?:string|null; fechado_em?:string|null; dinheiro_esperado?:number|string|null; dinheiro_contado?:number|string|null; diferenca_dinheiro?:number|string|null; total_entradas?:number|string|null; total_saidas?:number|string|null; resultado_liquido?:number|string|null; observacao_fechamento?:string|null }
type Movimento = { id:number|string; origem:string; tipo?:string; natureza:'ENTRADA'|'SAIDA'; forma:FormaCaixa; valor:number|string; descricao:string; criado_em:string; criado_por_nome?:string; status?:'ATIVO'|'ESTORNADO'; estorno_motivo?:string|null }
type Painel = { estruturaPendente:boolean; sessao:Sessao|null; resumo:ResumoCaixa|null; movimentosAutomaticos:Movimento[]; movimentosManuais:Movimento[]; historico:Sessao[] }
const vazio:Painel={estruturaPendente:false,sessao:null,resumo:null,movimentosAutomaticos:[],movimentosManuais:[],historico:[]}

export default function FechamentoCaixaPage(){
  const [painel,setPainel]=useState<Painel>(vazio),[loading,setLoading]=useState(true),[salvando,setSalvando]=useState(false)
  const [erro,setErro]=useState(''),[mensagem,setMensagem]=useState(''),[saldoInicial,setSaldoInicial]=useState('0,00'),[observacaoAbertura,setObservacaoAbertura]=useState('')
  const [tipo,setTipo]=useState('SANGRIA'),[forma,setForma]=useState<FormaCaixa>('DINHEIRO'),[valor,setValor]=useState(''),[descricao,setDescricao]=useState('')
  const [contado,setContado]=useState(''),[observacaoFechamento,setObservacaoFechamento]=useState(''),[detalhes,setDetalhes]=useState(false)

  const carregar=useCallback(async()=>{setLoading(true);setErro('');try{const r=await adminFetch('/api/admin/financeiro/caixa',{cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error??'Erro ao carregar o caixa.');setPainel(d);setContado((atual)=>atual||(!d?.resumo?'':num(d.resumo.dinheiroEsperado).toFixed(2).replace('.',',')))}catch(e){setErro(msg(e))}finally{setLoading(false)}},[])
  useEffect(()=>{void Promise.resolve().then(carregar)},[carregar])
  const consolidados=useMemo(()=>({semana:consolidar(painel.historico,7),mes:consolidarMes(painel.historico)}),[painel.historico])

  async function executar(body:Record<string,unknown>,sucesso:string){setSalvando(true);setErro('');setMensagem('');try{const r=await adminFetch('/api/admin/financeiro/caixa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error??'Nao foi possivel concluir.');setMensagem(sucesso);setValor('');setDescricao('');await carregar()}catch(e){setErro(msg(e))}finally{setSalvando(false)}}
  function abrir(e:FormEvent){e.preventDefault();void executar({acao:'ABRIR',saldoInicial:entrada(saldoInicial),observacao:observacaoAbertura},'Caixa aberto com sucesso.')}
  function movimentar(e:FormEvent){e.preventDefault();void executar({acao:'MOVIMENTO',tipo,forma,valor:entrada(valor),descricao},'Movimento registrado.')}
  function fechar(e:FormEvent){e.preventDefault();if(confirm('Confirma o encerramento deste caixa?'))void executar({acao:'FECHAR',dinheiroContado:entrada(contado),observacao:observacaoFechamento},'Caixa encerrado com sucesso.')}
  function estornar(item:Movimento){const motivo=prompt('Informe o motivo do estorno:');if(motivo?.trim())void executar({acao:'ESTORNAR',id:item.id,motivo},'Movimento estornado.')}
  if(loading&&!painel.sessao&&!painel.historico.length)return <main className="p-6 font-semibold text-slate-600">Carregando fechamento de caixa...</main>

  return <main className="min-h-screen bg-[#c7d3cf] p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-4">
    <header className="flex flex-col gap-3 rounded-2xl bg-slate-950 p-5 text-white md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.22em] text-orange-400">Operacao financeira</p><h1 className="text-2xl font-black">Fechamento de Caixa</h1><p className="mt-1 text-sm text-slate-300">Abertura, sangrias, suprimentos, conferencia e encerramento por unidade.</p></div><div className="flex gap-2"><Link href="/admin/financeiro" className="rounded-lg border border-slate-600 px-4 py-2 text-sm font-bold">Voltar</Link><button onClick={()=>void carregar()} className="rounded-lg bg-white px-4 py-2 text-sm font-black text-slate-950">Atualizar</button></div></header>
    {erro&&<Aviso cor="red">{erro}</Aviso>}{mensagem&&<Aviso cor="green">{mensagem}</Aviso>}{painel.estruturaPendente&&<Aviso cor="amber">Execute o arquivo <b>supabase-add-fechamento-caixa.sql</b> no Supabase.</Aviso>}

    {!painel.estruturaPendente&&!painel.sessao&&<section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={abrir} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase text-emerald-700">Inicio do expediente</p><h2 className="text-xl font-black">Abrir o caixa da unidade</h2><p className="text-sm text-slate-500">Informe somente o dinheiro fisico existente na gaveta.</p><Campo label="Saldo inicial em dinheiro"><input value={saldoInicial} onChange={e=>setSaldoInicial(e.target.value)} inputMode="decimal" className="campo text-lg font-black" required/></Campo><Campo label="Observacao"><textarea value={observacaoAbertura} onChange={e=>setObservacaoAbertura(e.target.value)} className="campo min-h-24" placeholder="Ex.: troco do fechamento anterior."/></Campo><button disabled={salvando} className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-3 font-black text-white disabled:opacity-50">Abrir caixa</button></form><Orientacao/></section>}

    {painel.sessao&&painel.resumo&&<><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase text-emerald-700"><span className="mr-2 inline-block h-3 w-3 animate-pulse rounded-full bg-emerald-500"/>Caixa aberto</p><h2 className="text-xl font-black">Aberto por {painel.sessao.aberto_por_nome}</h2><p className="text-sm text-slate-500">{dataHora(painel.sessao.aberto_em)} • inicial {moeda(num(painel.sessao.saldo_inicial_dinheiro))}</p></div><span className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-black text-emerald-700">Em operacao</span></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Card label="Entradas" valor={painel.resumo.totalEntradas} cor="green"/><Card label="Saidas" valor={painel.resumo.totalSaidas} cor="red"/><Card label="Movimento liquido" valor={painel.resumo.resultadoLiquido} cor="blue"/><Card label="Dinheiro esperado" valor={painel.resumo.dinheiroEsperado} cor="orange"/></div></section>
    <section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-4"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Movimento por forma</h2><p className="text-xs text-slate-500">Automaticos desde a abertura, somados aos movimentos manuais.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-2">Forma</th><th>Entradas</th><th>Saidas</th><th>Liquido</th></tr></thead><tbody>{FORMAS_CAIXA.map(f=><tr key={f} className="border-b border-slate-100"><td className="p-2 font-black">{rotulo(f)}</td><td className="font-bold text-emerald-700">{moeda(painel.resumo!.entradas[f])}</td><td className="font-bold text-red-700">{moeda(painel.resumo!.saidas[f])}</td><td className="font-black">{moeda(painel.resumo!.liquido[f])}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><button onClick={()=>setDetalhes(!detalhes)} className="flex w-full items-center justify-between text-left"><div><h2 className="text-lg font-black">Detalhamento</h2><p className="text-xs text-slate-500">{painel.movimentosAutomaticos.length} automaticos • {painel.movimentosManuais.length} manuais</p></div><b className="text-sm text-blue-700">{detalhes?'Ocultar':'Ver detalhes'}</b></button>{detalhes&&<div className="mt-4 max-h-[430px] space-y-2 overflow-y-auto">{[...painel.movimentosManuais,...painel.movimentosAutomaticos].sort((a,b)=>b.criado_em.localeCompare(a.criado_em)).map(m=><MovimentoLinha key={`${m.origem}-${m.id}`} item={m} estornar={estornar}/>)}</div>}</section></div>
    <div className="space-y-4"><form onSubmit={movimentar} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase text-blue-700">Movimento manual</p><h2 className="text-lg font-black">Sangria ou suprimento</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Campo label="Tipo"><select value={tipo} onChange={e=>{setTipo(e.target.value);if(['SANGRIA','SUPRIMENTO'].includes(e.target.value))setForma('DINHEIRO')}} className="campo"><option value="SANGRIA">Sangria de dinheiro</option><option value="SUPRIMENTO">Suprimento de dinheiro</option><option value="ENTRADA_MANUAL">Outra entrada</option><option value="SAIDA_MANUAL">Outra saida</option></select></Campo><Campo label="Forma"><select disabled={['SANGRIA','SUPRIMENTO'].includes(tipo)} value={forma} onChange={e=>setForma(e.target.value as FormaCaixa)} className="campo disabled:bg-slate-100">{FORMAS_CAIXA.map(f=><option key={f} value={f}>{rotulo(f)}</option>)}</select></Campo><Campo label="Valor"><input value={valor} onChange={e=>setValor(e.target.value)} inputMode="decimal" className="campo" placeholder="0,00" required/></Campo><Campo label="Motivo"><input value={descricao} onChange={e=>setDescricao(e.target.value)} className="campo" placeholder="Motivo obrigatorio" required/></Campo></div><button disabled={salvando} className="mt-4 w-full rounded-xl bg-blue-700 px-4 py-3 font-black text-white disabled:opacity-50">Registrar movimento</button></form>
    <form onSubmit={fechar} className="rounded-2xl border-2 border-orange-300 bg-orange-50 p-5 shadow-sm"><p className="text-xs font-black uppercase text-orange-700">Fim do expediente</p><h2 className="text-lg font-black">Conferir e fechar</h2><p className="text-sm text-slate-600">Conte a gaveta. Esperado: <b>{moeda(painel.resumo.dinheiroEsperado)}</b>.</p><Campo label="Dinheiro contado"><input value={contado} onChange={e=>setContado(e.target.value)} inputMode="decimal" className="campo text-lg font-black" required/></Campo><p className={`mt-2 text-sm font-black ${diferenca(contado,painel.resumo.dinheiroEsperado)===0?'text-emerald-700':'text-red-700'}`}>Diferenca: {moeda(diferenca(contado,painel.resumo.dinheiroEsperado))}</p><Campo label="Observacao/justificativa"><textarea value={observacaoFechamento} onChange={e=>setObservacaoFechamento(e.target.value)} className="campo min-h-20" placeholder="Obrigatoria se houver diferenca."/></Campo><button disabled={salvando} className="mt-4 w-full rounded-xl bg-orange-600 px-4 py-3 font-black text-white disabled:opacity-50">Encerrar caixa</button></form></div></section></>}

    {!painel.estruturaPendente&&<section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Consolidado dos fechamentos</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><ResumoPeriodo titulo="Ultimos 7 dias" dados={consolidados.semana}/><ResumoPeriodo titulo="Mes atual" dados={consolidados.mes}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-2">Data</th><th>Responsavel</th><th>Entradas</th><th>Saidas</th><th>Esperado</th><th>Contado</th><th>Diferenca</th><th>Observacao</th></tr></thead><tbody>{painel.historico.map(s=><tr key={s.id} className="border-b border-slate-100"><td className="p-2 font-bold">{dataHora(s.fechado_em)}</td><td>{s.fechado_por_nome??'-'}</td><td className="text-emerald-700">{moeda(num(s.total_entradas))}</td><td className="text-red-700">{moeda(num(s.total_saidas))}</td><td>{moeda(num(s.dinheiro_esperado))}</td><td className="font-bold">{moeda(num(s.dinheiro_contado))}</td><td className={`font-black ${num(s.diferenca_dinheiro)===0?'text-emerald-700':'text-red-700'}`}>{moeda(num(s.diferenca_dinheiro))}</td><td className="max-w-64 text-xs">{s.observacao_fechamento??'-'}</td></tr>)}{!painel.historico.length&&<tr><td colSpan={8} className="p-8 text-center text-slate-500">Nenhum caixa fechado ainda.</td></tr>}</tbody></table></div></section>}
  </div></main>
}

function Card({label,valor,cor}:{label:string;valor:number;cor:'green'|'red'|'blue'|'orange'}){const c={green:'bg-emerald-50 text-emerald-800',red:'bg-red-50 text-red-800',blue:'bg-blue-50 text-blue-800',orange:'bg-orange-50 text-orange-800 ring-2 ring-orange-300'};return <div className={`rounded-xl p-3 ${c[cor]}`}><p className="text-[10px] font-black uppercase">{label}</p><p className="mt-1 text-lg font-black">{moeda(valor)}</p></div>}
function MovimentoLinha({item,estornar}:{item:Movimento;estornar:(m:Movimento)=>void}){const cancelado=item.status==='ESTORNADO';return <div className={`flex justify-between gap-3 rounded-xl border p-3 ${cancelado?'bg-slate-100 opacity-60':''}`}><div><span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${item.natureza==='ENTRADA'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{item.natureza}</span><span className="ml-2 text-[10px] font-black text-slate-500">{rotulo(item.forma)} • {item.origem}</span><p className="mt-1 text-sm font-bold">{item.descricao}</p><p className="text-[11px] text-slate-500">{dataHora(item.criado_em)}{item.criado_por_nome?` • ${item.criado_por_nome}`:''}</p>{cancelado&&<p className="text-xs font-bold text-red-700">Estornado: {item.estorno_motivo}</p>}</div><div className="text-right"><b className={item.natureza==='ENTRADA'?'text-emerald-700':'text-red-700'}>{item.natureza==='ENTRADA'?'+':'-'} {moeda(num(item.valor))}</b>{item.origem==='MANUAL'&&!cancelado&&<button onClick={()=>estornar(item)} className="mt-2 block text-xs font-bold text-red-700">Estornar</button>}</div></div>}
function ResumoPeriodo({titulo,dados}:{titulo:string;dados:Total}){return <div className="rounded-xl border p-4"><div className="flex justify-between"><b>{titulo}</b><small>{dados.quantidade} fechamento(s)</small></div><div className="mt-3 grid grid-cols-2 gap-2"><Mini l="Entradas" v={dados.entradas}/><Mini l="Saidas" v={dados.saidas}/><Mini l="Resultado" v={dados.resultado}/><Mini l="Diferencas" v={dados.diferencas} alerta={dados.diferencas!==0}/></div></div>}
function Mini({l,v,alerta}:{l:string;v:number;alerta?:boolean}){return <div className="rounded-lg bg-slate-50 p-2"><p className="text-[10px] font-black uppercase text-slate-500">{l}</p><b className={alerta?'text-red-700':''}>{moeda(v)}</b></div>}
function Campo({label,children}:{label:string;children:ReactNode}){return <label className="mt-4 block text-xs font-black uppercase text-slate-600">{label}{children}</label>}
function Aviso({cor,children}:{cor:'red'|'green'|'amber';children:ReactNode}){return <div className={`rounded-xl px-4 py-3 text-sm font-semibold ${cor==='red'?'bg-red-50 text-red-700':cor==='green'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{children}</div>}
function Orientacao(){return <section className="rounded-2xl bg-slate-900 p-5 text-white"><p className="text-xs font-black uppercase text-orange-400">Como funciona</p><h2 className="text-xl font-black">Um fechamento por unidade</h2><ol className="mt-4 space-y-3 text-sm text-slate-300"><li><b className="text-white">1. Abra</b> com o troco em dinheiro.</li><li><b className="text-white">2. Trabalhe normalmente.</b> Recebimentos, vendas e pagamentos entram automaticamente.</li><li><b className="text-white">3. Registre</b> sangrias e suprimentos.</li><li><b className="text-white">4. Conte</b> o dinheiro e encerre.</li></ol><p className="mt-5 rounded-xl bg-slate-800 p-3 text-xs">PIX, cartao, boleto e deposito sao conferidos separadamente. “Dinheiro esperado” e somente a gaveta fisica.</p></section>}
type Total={quantidade:number;entradas:number;saidas:number;resultado:number;diferencas:number}
function somar(itens:Sessao[]):Total{return itens.reduce((a,s)=>({quantidade:a.quantidade+1,entradas:a.entradas+num(s.total_entradas),saidas:a.saidas+num(s.total_saidas),resultado:a.resultado+num(s.resultado_liquido),diferencas:a.diferencas+num(s.diferenca_dinheiro)}),{quantidade:0,entradas:0,saidas:0,resultado:0,diferencas:0})}
function consolidar(itens:Sessao[],dias:number){const limite=Date.now()-dias*86400000;return somar(itens.filter(s=>new Date(s.fechado_em??0).getTime()>=limite))}
function consolidarMes(itens:Sessao[]){const h=new Date();return somar(itens.filter(s=>{const d=new Date(s.fechado_em??0);return d.getFullYear()===h.getFullYear()&&d.getMonth()===h.getMonth()}))}
function diferenca(v:string,e:number){return Math.round((entrada(v)-e+Number.EPSILON)*100)/100} function entrada(v:string){return Number(v.trim().replace(/\./g,'').replace(',','.'))||0} function num(v:unknown){return Number(v??0)||0}
function moeda(v:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)} function dataHora(v?:string|null){return v?new Date(v).toLocaleString('pt-BR'):'-'} function msg(e:unknown){return e instanceof Error?e.message:'Ocorreu um erro inesperado.'}
function rotulo(f:FormaCaixa){return({DINHEIRO:'Dinheiro',PIX:'PIX',CARTAO:'Cartao',BOLETO:'Boleto',DEPOSITO:'Deposito/transferencia',OUTROS:'Outros'})[f]}
