-- Cadastro permanente de equipamentos, histórico por equipamento e garantia ASC.
-- Execute uma vez no SQL Editor do Supabase antes de publicar esta etapa.

create table if not exists public.equipamentos_clientes (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete restrict,
  categoria_id bigint references public.categorias(id) on delete set null,
  marca_id bigint references public.marcas(id) on delete set null,
  modelo text not null,
  numero_serie text,
  numero_serie_normalizada text generated always as (
    upper(regexp_replace(coalesce(numero_serie, ''), '[^a-zA-Z0-9]', '', 'g'))
  ) stored,
  observacao text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create unique index if not exists equipamentos_clientes_serie_unica
  on public.equipamentos_clientes (numero_serie_normalizada)
  where numero_serie_normalizada <> '';

create index if not exists equipamentos_clientes_cliente_idx
  on public.equipamentos_clientes (cliente_id, ativo);

alter table public.equipamentos_clientes enable row level security;

alter table public.ordens_servico
  add column if not exists equipamento_id bigint references public.equipamentos_clientes(id) on delete set null,
  add column if not exists garantia_asc boolean not null default false,
  add column if not exists garantia_asc_origem_os_id bigint references public.ordens_servico(id) on delete set null,
  add column if not exists garantia_asc_confirmada_em timestamptz,
  add column if not exists garantia_asc_observacao text;

create index if not exists ordens_servico_equipamento_idx
  on public.ordens_servico (equipamento_id, created_at desc);

-- Migração segura: equipamentos antigos só são agrupados automaticamente quando
-- existe número de série. OS sem série continuam intactas e poderão ser vinculadas
-- manualmente, evitando juntar dois aparelhos iguais do mesmo cliente.
insert into public.equipamentos_clientes (
  cliente_id,
  categoria_id,
  marca_id,
  modelo,
  numero_serie,
  criado_em
)
select distinct on (
  upper(regexp_replace(coalesce(os.numero_serie, ''), '[^a-zA-Z0-9]', '', 'g'))
)
  os.cliente_id,
  os.categoria_id,
  os.marca_id,
  coalesce(nullif(trim(os.modelo), ''), 'Equipamento sem modelo'),
  trim(os.numero_serie),
  coalesce(os.created_at, now())
from public.ordens_servico os
where os.cliente_id is not null
  and nullif(trim(coalesce(os.numero_serie, '')), '') is not null
  and not exists (
    select 1
    from public.equipamentos_clientes equipamento
    where equipamento.numero_serie_normalizada =
      upper(regexp_replace(coalesce(os.numero_serie, ''), '[^a-zA-Z0-9]', '', 'g'))
  )
order by
  upper(regexp_replace(coalesce(os.numero_serie, ''), '[^a-zA-Z0-9]', '', 'g')),
  os.created_at asc;

update public.ordens_servico os
set equipamento_id = equipamento.id
from public.equipamentos_clientes equipamento
where os.equipamento_id is null
  and os.cliente_id = equipamento.cliente_id
  and nullif(trim(coalesce(os.numero_serie, '')), '') is not null
  and equipamento.numero_serie_normalizada =
    upper(regexp_replace(coalesce(os.numero_serie, ''), '[^a-zA-Z0-9]', '', 'g'));

comment on table public.equipamentos_clientes is
  'Cadastro permanente dos equipamentos dos clientes, compartilhado entre as unidades.';
comment on column public.ordens_servico.equipamento_id is
  'Equipamento permanente associado à OS; os campos antigos da OS permanecem como fotografia histórica.';
comment on column public.ordens_servico.garantia_asc is
  'Indica retorno confirmado em garantia da própria assistência técnica.';
