-- Recebimento conjunto de várias OS do mesmo cliente ou garantidor.
-- Execute uma vez no SQL Editor do Supabase.

create table if not exists public.recebimentos_lotes (
  id uuid primary key default gen_random_uuid(),
  tipo_pagador text not null check (tipo_pagador in ('CLIENTE', 'GARANTIDOR')),
  cliente_id bigint references public.clientes(id) on delete set null,
  garantidor_id bigint references public.garantidores(id) on delete set null,
  unidade_id bigint references public.unidades(id) on delete set null,
  forma_recebimento text not null,
  total_principal numeric(14,2) not null default 0,
  total_juros numeric(14,2) not null default 0,
  total_multa numeric(14,2) not null default 0,
  total_desconto numeric(14,2) not null default 0,
  total_iss_retido numeric(14,2) not null default 0,
  total_caixa numeric(14,2) not null default 0,
  quantidade_os integer not null default 0,
  status text not null default 'PROCESSANDO',
  responsavel text,
  criado_em timestamptz not null default now(),
  concluido_em timestamptz
);

create table if not exists public.recebimentos_lotes_itens (
  id bigint generated by default as identity primary key,
  lote_id uuid not null references public.recebimentos_lotes(id) on delete cascade,
  os_id bigint not null references public.ordens_servico(id) on delete restrict,
  valor_principal numeric(14,2) not null default 0,
  juros numeric(14,2) not null default 0,
  multa numeric(14,2) not null default 0,
  desconto numeric(14,2) not null default 0,
  iss_retido numeric(14,2) not null default 0,
  valor_caixa numeric(14,2) not null default 0,
  status_anterior text,
  status_novo text not null,
  criado_em timestamptz not null default now(),
  unique (lote_id, os_id)
);

alter table public.recebimentos_lotes enable row level security;
alter table public.recebimentos_lotes_itens enable row level security;

alter table public.financeiro_historico
  add column if not exists lote_id uuid references public.recebimentos_lotes(id) on delete set null;

create index if not exists recebimentos_lotes_pagador_idx
  on public.recebimentos_lotes (tipo_pagador, cliente_id, garantidor_id, criado_em desc);
create index if not exists recebimentos_lotes_itens_os_idx
  on public.recebimentos_lotes_itens (os_id, criado_em desc);

comment on table public.recebimentos_lotes is
  'Cabeçalho auditável de recebimentos envolvendo várias OS do mesmo pagador.';
