import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { requireAdminUnidade } from '@/lib/admin-unidade'

const url = process.env.NEXT_PUBLIC_SUPABASE_URL
const key = process.env.SUPABASE_SERVICE_ROLE_KEY
function db(){ if(!url||!key) throw new Error('Supabase não configurado.'); return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}) }
export async function GET(request:NextRequest){ try { const auth=await requireAdminUnidade(request,'pecas'); if(!auth.ok)return auth.response; const supabase=db(); const {error: pendente}=await supabase.from('estoque_transferencias').select('id').limit(0); if(pendente)return NextResponse.json({estruturaPendente:true,pecas:[],empresas:[],transferencias:[]}); const [p,u,t]=await Promise.all([supabase.from('pecas').select('id,codigo,descricao,estoque').eq('unidade_id',auth.unidadeId).gt('estoque',0).order('descricao'),supabase.from('unidades').select('id,nome_fantasia').in('id',auth.unidadesPermitidas).neq('id',auth.unidadeId).eq('ativa',true),supabase.from('estoque_transferencias').select('id,quantidade,observacao,criado_em,unidade_origem_id,unidade_destino_id,pecas:peca_origem_id(descricao,codigo),origem:unidade_origem_id(nome_fantasia),destino:unidade_destino_id(nome_fantasia)').or(`unidade_origem_id.eq.${auth.unidadeId},unidade_destino_id.eq.${auth.unidadeId}`).order('criado_em',{ascending:false}).limit(30)]); if(p.error||u.error||t.error)throw p.error||u.error||t.error; return NextResponse.json({estruturaPendente:false,pecas:p.data??[],empresas:u.data??[],transferencias:t.data??[]}) }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao carregar transferências.'},{status:500})} }
export async function POST(request:NextRequest){try{const auth=await requireAdminUnidade(request,'pecas');if(!auth.ok)return auth.response;const b=await request.json();const destino=Number(b?.unidadeDestinoId),peca=Number(b?.pecaId),q=Number(b?.quantidade);if(!auth.unidadesPermitidas.includes(destino)||!peca||!Number.isFinite(q)||q<=0)return NextResponse.json({error:'Informe uma empresa permitida, peça e quantidade válida.'},{status:400});const {data,error}=await db().rpc('transferir_estoque_entre_empresas',{p_unidade_origem:auth.unidadeId,p_unidade_destino:destino,p_peca_origem:peca,p_quantidade:q,p_observacao:String(b?.observacao??''),p_responsavel:auth.nome??auth.email??''});if(error)throw error;return NextResponse.json({ok:true,id:data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao transferir estoque.'},{status:400})}}
