'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { adminFetch } from '@/lib/admin-fetch'

type Conta = { id: number; nome: string; tipo: string; banco?: string | null; agencia?: string | null; numero_conta?: string | null; saldo_inicial: number | string; saldo_atual?: number | string; ativa: boolean; padrao_dinheiro: boolean }
type Operadora = { id: number; nome: string; ativa: boolean; conta_recebimento_id: number; contas_financeiras?: { nome?: string } | Array<{ nome?: string }> | null }
type Taxa = { id: number; operadora_id: number; modalidade: string; parcelas_de: number; parcelas_ate: number; taxa_percentual: number | string; taxa_fixa: number | string; prazo_dias: number; ativa: boolean }
type Movimento = { id: number; natureza: string; tipo: string; forma: string; valor_bruto: number | string; taxa_valor: number | string; valor_liquido: number | string; descricao: string; criado_em: string; contas_financeiras?: { nome?: string } | Array<{ nome?: string }> | null }

export default function ContasFinanceirasPage() {
  const [contas, setContas] = useState<Conta[]>([]); const [operadoras, setOperadoras] = useState<Operadora[]>([]); const [taxas, setTaxas] = useState<Taxa[]>([]); const [movimentos, setMovimentos] = useState<Movimento[]>([])
  const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState(''); const [salvando, setSalvando] = useState(false); const [estruturaPendente, setEstruturaPendente] = useState(false)
  const [conta, setConta] = useState({ nome: '', tipo: 'BANCO', banco: '', agencia: '', numeroConta: '', chavePix: '', saldoInicial: '0', padraoDinheiro: false })
  const [operadora, setOperadora] = useState({ nome: '', contaId: '' }); const [taxa, setTaxa] = useState({ operadoraId: '', modalidade: 'CREDITO', parcelasDe: '1', parcelasAte: '1', taxaPercentual: '0', taxaFixa: '0', prazoDias: '30' })
  const [transferencia, setTransferencia] = useState({ origemId: '', destinoId: '', valor: '', descricao: '' })
  const carregar = useCallback(async () => { try { const response = await adminFetch('/api/admin/financeiro/contas'); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Erro ao carregar contas.'); setContas(payload?.contas ?? []); setOperadoras(payload?.operadoras ?? []); setTaxas(payload?.taxas ?? []); setMovimentos(payload?.movimentos ?? []); setEstruturaPendente(Boolean(payload?.estruturaPendente)) } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao carregar contas.') } }, [])
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void carregar()
  }, [carregar])
  const contasAtivas = useMemo(() => contas.filter((item) => item.ativa), [contas])
  async function enviar(method: 'POST' | 'PATCH', body: Record<string, unknown>, sucesso: string) { setSalvando(true); setErro(''); setMensagem(''); try { const response = await adminFetch('/api/admin/financeiro/contas', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Operação não concluída.'); setMensagem(sucesso); await carregar() } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao salvar.') } finally { setSalvando(false) } }
  return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-[1550px] space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-orange-600">Tesouraria</p><h1 className="text-3xl font-black">Contas, cartões e taxas</h1><p className="text-sm text-slate-500">Controle onde o dinheiro entra, sai e qual valor líquido será creditado.</p></div><Link href="/admin/financeiro" className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Voltar ao Financeiro</Link></header>
    {estruturaPendente && <Aviso cor="amber">Execute o arquivo supabase-add-fechamento-caixa.sql no Supabase para liberar esta área.</Aviso>}{erro && <Aviso cor="red">{erro}</Aviso>}{mensagem && <Aviso cor="green">{mensagem}</Aviso>}
    <div className="grid gap-5 xl:grid-cols-3">
      <Card titulo="Nova conta financeira"><Campo label="Nome"><input className="campo" value={conta.nome} onChange={(e) => setConta({ ...conta, nome: e.target.value })} /></Campo><Campo label="Tipo"><select className="campo" value={conta.tipo} onChange={(e) => setConta({ ...conta, tipo: e.target.value })}><option value="BANCO">Conta bancária</option><option value="CAIXA">Caixa físico</option><option value="CARTEIRA_DIGITAL">Carteira digital</option><option value="ADQUIRENTE">Cartões a receber</option></select></Campo><div className="grid grid-cols-2 gap-2"><Campo label="Banco"><input className="campo" value={conta.banco} onChange={(e) => setConta({ ...conta, banco: e.target.value })} /></Campo><Campo label="Saldo inicial"><input type="number" step="0.01" className="campo" value={conta.saldoInicial} onChange={(e) => setConta({ ...conta, saldoInicial: e.target.value })} /></Campo></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={conta.padraoDinheiro} onChange={(e) => setConta({ ...conta, padraoDinheiro: e.target.checked })} />Conta padrão para dinheiro</label><Botao onClick={() => void enviar('POST', { acao: 'CONTA', ...conta }, 'Conta cadastrada.')} disabled={salvando || !conta.nome}>Cadastrar conta</Botao></Card>
      <Card titulo="Nova operadora"><Campo label="Nome da operadora"><input className="campo" placeholder="Stone, Cielo, Asaas..." value={operadora.nome} onChange={(e) => setOperadora({ ...operadora, nome: e.target.value })} /></Campo><Campo label="Conta que receberá os cartões"><select className="campo" value={operadora.contaId} onChange={(e) => setOperadora({ ...operadora, contaId: e.target.value })}><option value="">Selecione</option>{contasAtivas.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Campo><Botao onClick={() => void enviar('POST', { acao: 'OPERADORA', ...operadora }, 'Operadora cadastrada.')} disabled={salvando || !operadora.nome || !operadora.contaId}>Cadastrar operadora</Botao></Card>
      <Card titulo="Taxa da operadora"><Campo label="Operadora"><select className="campo" value={taxa.operadoraId} onChange={(e) => setTaxa({ ...taxa, operadoraId: e.target.value })}><option value="">Selecione</option>{operadoras.filter((item) => item.ativa).map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Campo><Campo label="Modalidade"><select className="campo" value={taxa.modalidade} onChange={(e) => setTaxa({ ...taxa, modalidade: e.target.value })}><option value="DEBITO">Débito</option><option value="CREDITO">Crédito</option><option value="PIX">PIX da operadora</option></select></Campo><div className="grid grid-cols-2 gap-2"><Campo label="Parcelas de"><input type="number" min="1" max="24" className="campo" value={taxa.parcelasDe} onChange={(e) => setTaxa({ ...taxa, parcelasDe: e.target.value })} /></Campo><Campo label="Até"><input type="number" min="1" max="24" className="campo" value={taxa.parcelasAte} onChange={(e) => setTaxa({ ...taxa, parcelasAte: e.target.value })} /></Campo><Campo label="Taxa %"><input type="number" step="0.0001" className="campo" value={taxa.taxaPercentual} onChange={(e) => setTaxa({ ...taxa, taxaPercentual: e.target.value })} /></Campo><Campo label="Taxa fixa"><input type="number" step="0.01" className="campo" value={taxa.taxaFixa} onChange={(e) => setTaxa({ ...taxa, taxaFixa: e.target.value })} /></Campo></div><Campo label="Prazo para crédito (dias)"><input type="number" min="0" className="campo" value={taxa.prazoDias} onChange={(e) => setTaxa({ ...taxa, prazoDias: e.target.value })} /></Campo><Botao onClick={() => void enviar('POST', { acao: 'TAXA', ...taxa }, 'Taxa salva.')} disabled={salvando || !taxa.operadoraId}>Salvar taxa</Botao></Card>
    </div>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Contas cadastradas</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{contas.map((item) => <div key={item.id} className={`rounded-xl border p-4 ${item.ativa ? 'border-slate-200' : 'bg-slate-100 opacity-60'}`}><div className="flex justify-between gap-2"><div><p className="font-black">{item.nome}</p><p className="text-xs font-bold text-slate-500">{item.tipo.replaceAll('_', ' ')}</p></div>{item.padrao_dinheiro && <span className="h-fit rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-black text-emerald-700">PADRÃO</span>}</div><p className="mt-3 text-xs font-bold uppercase text-slate-500">Saldo atual</p><p className="text-xl font-black text-slate-950">{moeda(item.saldo_atual ?? item.saldo_inicial)}</p><p className="mt-1 text-xs text-slate-500">Saldo inicial: {moeda(item.saldo_inicial)}</p><button onClick={() => void enviar('PATCH', { tipo: 'CONTA', id: item.id, ativa: !item.ativa }, item.ativa ? 'Conta desativada.' : 'Conta ativada.')} className="mt-3 text-xs font-black text-blue-700">{item.ativa ? 'Desativar' : 'Ativar'}</button></div>)}</div></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Taxas cadastradas</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="p-2">Operadora</th><th>Modalidade</th><th>Parcelas</th><th>Taxa</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{taxas.map((item) => <tr key={item.id} className="border-t"><td className="p-2 font-black">{operadoras.find((op) => op.id === item.operadora_id)?.nome}</td><td>{item.modalidade}</td><td>{item.parcelas_de === item.parcelas_ate ? item.parcelas_de : `${item.parcelas_de} a ${item.parcelas_ate}`}</td><td>{numero(item.taxa_percentual).toFixed(4)}% + {moeda(item.taxa_fixa)}</td><td>D+{item.prazo_dias}</td><td>{item.ativa ? 'Ativa' : 'Inativa'}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-5 lg:grid-cols-[420px_1fr]"><Card titulo="Transferir entre contas"><Campo label="Conta de origem"><select className="campo" value={transferencia.origemId} onChange={(e) => setTransferencia({ ...transferencia, origemId: e.target.value })}><option value="">Selecione</option>{contasAtivas.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Campo><Campo label="Conta de destino"><select className="campo" value={transferencia.destinoId} onChange={(e) => setTransferencia({ ...transferencia, destinoId: e.target.value })}><option value="">Selecione</option>{contasAtivas.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Campo><Campo label="Valor"><input type="number" step="0.01" className="campo" value={transferencia.valor} onChange={(e) => setTransferencia({ ...transferencia, valor: e.target.value })} /></Campo><Botao onClick={() => void enviar('POST', { acao: 'TRANSFERENCIA', ...transferencia }, 'Transferência registrada.')} disabled={salvando || !transferencia.origemId || !transferencia.destinoId}>Transferir</Botao></Card><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Últimos movimentos</h2><div className="mt-3 max-h-[410px] overflow-auto">{movimentos.map((item) => <div key={item.id} className="flex justify-between gap-3 border-b py-3 text-sm"><div><p className="font-black">{item.descricao}</p><p className="text-xs text-slate-500">{relacao(item.contas_financeiras)?.nome} · {new Date(item.criado_em).toLocaleString('pt-BR')}</p></div><p className={`font-black ${item.natureza === 'ENTRADA' ? 'text-emerald-700' : 'text-red-700'}`}>{item.natureza === 'ENTRADA' ? '+' : '-'} {moeda(item.valor_liquido)}</p></div>)}</div></section></div>
  </div></main>
}

function Card({ titulo, children }: { titulo: string; children: ReactNode }) { return <section className="space-y-3 rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-black">{titulo}</h2>{children}</section> }
function Campo({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-black text-slate-600">{label}<div className="mt-1">{children}</div></label> }
function Botao({ onClick, disabled, children }: { onClick: () => void; disabled?: boolean; children: ReactNode }) { return <button type="button" onClick={onClick} disabled={disabled} className="w-full rounded-xl bg-orange-500 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{children}</button> }
function Aviso({ cor, children }: { cor: 'red' | 'green' | 'amber'; children: ReactNode }) { const classe = cor === 'red' ? 'bg-red-50 text-red-700' : cor === 'green' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'; return <div className={`rounded-xl p-4 text-sm font-bold ${classe}`}>{children}</div> }
function relacao<T>(v?: T | T[] | null) { return Array.isArray(v) ? v[0] : v }
function numero(v: unknown) { return Number(v ?? 0) || 0 }
function moeda(v: unknown) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(numero(v)) }
