'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { adminFetch } from '@/lib/admin-fetch'

type Relacao = { nome?: string | null } | Array<{ nome?: string | null }> | null
type Ordem = { id: number; numero_os?: string | null; status_financeiro?: string | null; total?: number | string | null; cliente_total?: number | string | null; valor_recebido_cliente?: number | string | null; desconto_recebimento_cliente?: number | string | null; clientes?: Relacao }
type Parcela = { id: number; os_id: number; numero_parcela: number; total_parcelas: number; valor: number | string; vencimento: string; status: string; recebido_em?: string | null; criado_por: string; recebido_por?: string | null; ordens_servico?: { numero_os?: string | null; clientes?: Relacao } | null }

export default function ParcelamentosPage() {
  const [ordens, setOrdens] = useState<Ordem[]>([]); const [parcelas, setParcelas] = useState<Parcela[]>([])
  const [estruturaPendente, setEstruturaPendente] = useState(false); const [loading, setLoading] = useState(true); const [salvando, setSalvando] = useState(false)
  const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState(''); const [osId, setOsId] = useState(''); const [quantidade, setQuantidade] = useState('2'); const [vencimento, setVencimento] = useState(hoje())

  const carregar = useCallback(async () => { setLoading(true); setErro(''); try { const response = await adminFetch('/api/admin/parcelamentos'); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Erro ao carregar parcelamentos.'); setOrdens(payload?.ordens ?? []); setParcelas(payload?.parcelas ?? []); setEstruturaPendente(Boolean(payload?.estruturaPendente)) } catch (error) { setErro(error instanceof Error ? error.message : 'Erro ao carregar parcelamentos.') } finally { setLoading(false) } }, [])
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void carregar()
  }, [carregar])

  const ordensDisponiveis = useMemo(() => ordens.filter((os) => saldo(os) > 0 && !parcelas.some((p) => p.os_id === os.id && p.status !== 'CANCELADO')), [ordens, parcelas])
  const grupos = useMemo(() => { const map = new Map<number, Parcela[]>(); for (const parcela of parcelas) map.set(parcela.os_id, [...(map.get(parcela.os_id) ?? []), parcela]); return [...map.entries()].map(([id, itens]) => ({ id, itens })) }, [parcelas])

  async function requisicao(method: 'POST' | 'PATCH', body: Record<string, unknown>, sucesso: string) { setSalvando(true); setErro(''); setMensagem(''); try { const response = await adminFetch('/api/admin/parcelamentos', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Operação não concluída.'); setMensagem(sucesso); await carregar() } catch (error) { setErro(error instanceof Error ? error.message : 'Erro ao atualizar parcelamento.') } finally { setSalvando(false) } }
  function criar() { if (!osId) return setErro('Selecione uma OS.'); void requisicao('POST', { osId: Number(osId), quantidade: Number(quantidade), primeiroVencimento: vencimento }, 'Parcelamento criado com sucesso.') }

  return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-black text-slate-950">Recebimentos parcelados</h1><p className="text-sm text-slate-500">Controle individual de boletos, vencimentos e baixas</p></div><Link href="/admin/financeiro" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Voltar ao Financeiro</Link></header>
  {estruturaPendente && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">Execute o arquivo supabase-add-recebimento-parcelado.sql no Supabase para liberar esta área.</div>}{erro && <div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{erro}</div>}{mensagem && <div className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{mensagem}</div>}
  <section className="rounded-xl bg-white p-4 shadow-sm"><h2 className="mb-3 text-lg font-black">Novo parcelamento em boleto</h2><div className="grid gap-3 lg:grid-cols-[2fr_150px_180px_auto]"><Campo label="OS"><select value={osId} onChange={(e) => setOsId(e.target.value)} className="input"><option value="">Selecione uma OS com saldo</option>{ordensDisponiveis.map((os) => <option key={os.id} value={os.id}>{os.numero_os} • {nomeCliente(os.clientes)} • saldo {moeda(saldo(os))}</option>)}</select></Campo><Campo label="Parcelas"><input type="number" min="2" max="60" value={quantidade} onChange={(e) => setQuantidade(e.target.value)} className="input" /></Campo><Campo label="1º vencimento"><input type="date" value={vencimento} onChange={(e) => setVencimento(e.target.value)} className="input" /></Campo><button type="button" disabled={salvando || estruturaPendente} onClick={criar} className="self-end rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">Gerar parcelas</button></div></section>
  <section className="rounded-xl bg-white p-4 shadow-sm"><h2 className="mb-3 text-lg font-black">Parcelamentos cadastrados</h2>{loading ? <p className="text-sm text-slate-500">Carregando...</p> : grupos.length === 0 ? <p className="text-sm text-slate-500">Nenhum parcelamento cadastrado.</p> : <div className="space-y-4">{grupos.map(({ id, itens }) => { const primeira = itens[0]; const pendente = itens.filter((p) => p.status === 'PENDENTE').reduce((a, p) => a + Number(p.valor), 0); return <div key={id} className="overflow-hidden rounded-xl border border-slate-200"><div className="flex flex-col gap-2 bg-slate-50 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-slate-950">{primeira.ordens_servico?.numero_os ?? `OS #${id}`} • {nomeCliente(primeira.ordens_servico?.clientes)}</p><p className="text-xs font-semibold text-slate-500">{itens.length} parcelas • criado por {primeira.criado_por}</p></div><p className="font-black text-orange-700">Em aberto: {moeda(pendente)}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="p-3">Parcela</th><th className="p-3">Vencimento</th><th className="p-3">Valor</th><th className="p-3">Forma</th><th className="p-3">Situação</th><th className="p-3">Baixa</th><th className="p-3">Ações</th></tr></thead><tbody>{itens.map((p) => <tr key={p.id} className="border-t"><td className="p-3 font-bold">{p.numero_parcela}/{p.total_parcelas}</td><td className={`p-3 ${vencida(p) ? 'font-bold text-red-700' : ''}`}>{dataPt(p.vencimento)}</td><td className="p-3 font-black">{moeda(Number(p.valor))}</td><td className="p-3">BOLETO</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-black ${p.status === 'RECEBIDO' ? 'bg-emerald-100 text-emerald-700' : p.status === 'CANCELADO' ? 'bg-slate-100 text-slate-600' : vencida(p) ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'}`}>{p.status === 'PENDENTE' && vencida(p) ? 'VENCIDO' : p.status}</span></td><td className="p-3 text-xs">{p.recebido_em ? `${dataHora(p.recebido_em)} • ${p.recebido_por ?? '-'}` : '-'}</td><td className="p-3">{p.status === 'PENDENTE' && <div className="flex gap-2"><button disabled={salvando} onClick={() => void requisicao('PATCH', { id: p.id, acao: 'RECEBER' }, `Parcela ${p.numero_parcela}/${p.total_parcelas} recebida.`)} className="rounded bg-emerald-600 px-3 py-1.5 text-xs font-black text-white">Receber</button><button disabled={salvando} onClick={() => void requisicao('PATCH', { id: p.id, acao: 'CANCELAR' }, 'Parcela cancelada.')} className="rounded border border-slate-300 px-3 py-1.5 text-xs font-black">Cancelar</button></div>}</td></tr>)}</tbody></table></div></div> })}</div>}</section>
  </div><style jsx>{`.input{height:42px;width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:0 12px;font-size:14px}`}</style></main>
}
function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-black text-slate-600">{label}<div className="mt-1">{children}</div></label> }
function saldo(os: Ordem) { return Math.max(Number(os.cliente_total ?? os.total ?? 0) - Number(os.valor_recebido_cliente ?? 0) - Number(os.desconto_recebimento_cliente ?? 0), 0) }
function nomeCliente(relacao?: Relacao) { const item = Array.isArray(relacao) ? relacao[0] : relacao; return item?.nome ?? '-' }
function moeda(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value) }
function hoje() { return new Date().toISOString().slice(0, 10) }
function dataPt(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') }
function dataHora(value: string) { return new Date(value).toLocaleString('pt-BR') }
function vencida(parcela: Parcela) { return parcela.status === 'PENDENTE' && parcela.vencimento < hoje() }
