'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { adminFetch } from '@/lib/admin-fetch'

type Peca = { id: number; codigo?: string | null; descricao: string; categoria?: string | null; marca?: string | null; valor_venda?: number | string | null; estoque?: number | string | null }
type Cliente = { id: number; nome?: string | null; cpf_cnpj?: string | null; whatsapp?: string | null }
type Carrinho = { peca: Peca; quantidade: number; valorUnitario: number; desconto: number }
type Venda = { id: number; numero_venda: string; subtotal: number | string; desconto: number | string; total: number | string; forma_recebimento: string; status: string; observacao?: string | null; criado_por_nome: string; criado_em: string; cancelamento_motivo?: string | null; clientes?: Cliente | Cliente[] | null }
type ItemVenda = { id: number; venda_id: number; descricao: string; codigo?: string | null; quantidade: number | string; valor_unitario: number | string; desconto: number | string; total_item: number | string }

export default function VendasPage() {
  const [pecas, setPecas] = useState<Peca[]>([]); const [clientes, setClientes] = useState<Cliente[]>([]); const [vendas, setVendas] = useState<Venda[]>([]); const [itensVenda, setItensVenda] = useState<ItemVenda[]>([])
  const [carrinho, setCarrinho] = useState<Carrinho[]>([]); const [busca, setBusca] = useState(''); const [clienteId, setClienteId] = useState(''); const [forma, setForma] = useState('PIX'); const [desconto, setDesconto] = useState('0'); const [observacao, setObservacao] = useState('')
  const [estruturaPendente, setEstruturaPendente] = useState(false); const [loading, setLoading] = useState(true); const [salvando, setSalvando] = useState(false); const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState('')

  const carregar = useCallback(async () => { setLoading(true); setErro(''); try { const response = await adminFetch('/api/admin/vendas'); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Erro ao carregar vendas.'); setPecas(payload?.pecas ?? []); setClientes(payload?.clientes ?? []); setVendas(payload?.vendas ?? []); setItensVenda(payload?.itens ?? []); setEstruturaPendente(Boolean(payload?.estruturaPendente)) } catch (error) { setErro(error instanceof Error ? error.message : 'Erro ao carregar vendas.') } finally { setLoading(false) } }, [])
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void carregar()
  }, [carregar])
  const filtradas = useMemo(() => { const termo = busca.toLowerCase().trim(); return pecas.filter((p) => Number(p.estoque ?? 0) > 0 && (!termo || `${p.codigo ?? ''} ${p.descricao} ${p.categoria ?? ''} ${p.marca ?? ''}`.toLowerCase().includes(termo))) }, [busca, pecas])
  const subtotal = carrinho.reduce((a, i) => a + i.quantidade * i.valorUnitario, 0); const descontosItens = carrinho.reduce((a, i) => a + i.desconto, 0); const total = Math.max(subtotal - descontosItens - numero(desconto), 0)

  function adicionar(peca: Peca) { setCarrinho((atual) => { const existente = atual.find((i) => i.peca.id === peca.id); if (existente) return atual.map((i) => i.peca.id === peca.id ? { ...i, quantidade: Math.min(i.quantidade + 1, Number(peca.estoque)) } : i); return [...atual, { peca, quantidade: 1, valorUnitario: Number(peca.valor_venda ?? 0), desconto: 0 }] }) }
  function adicionarAvulso() { const descricao = window.prompt('Descrição do item avulso:')?.trim(); if (!descricao) return; const valorInformado = window.prompt('Valor unitário do item:', '0,00'); if (valorInformado === null) return; const valorUnitario = numero(valorInformado); if (valorUnitario < 0) return setErro('Informe um valor válido para o item avulso.'); setErro(''); setCarrinho((atual) => [...atual, { peca: { id: -Date.now(), codigo: 'AVULSO', descricao, categoria: 'Item avulso', estoque: 999999 }, quantidade: 1, valorUnitario, desconto: 0 }]) }
  function atualizar(id: number, campo: 'quantidade' | 'valorUnitario' | 'desconto', valor: number) { setCarrinho((atual) => atual.map((i) => i.peca.id === id ? { ...i, [campo]: Math.max(0, campo === 'quantidade' ? Math.min(valor, Number(i.peca.estoque)) : valor) } : i)) }
  function remover(id: number) { setCarrinho((atual) => atual.filter((i) => i.peca.id !== id)) }
  async function finalizar() { if (!carrinho.length) return setErro('Adicione produtos ao carrinho.'); setSalvando(true); setErro(''); setMensagem(''); try { const response = await adminFetch('/api/admin/vendas', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clienteId: Number(clienteId) || null, formaRecebimento: forma, desconto: numero(desconto), observacao, itens: carrinho.map((i) => ({ pecaId: i.peca.id, descricao: i.peca.descricao, quantidade: i.quantidade, valorUnitario: i.valorUnitario, desconto: i.desconto })) }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Erro ao finalizar venda.'); setMensagem(`Venda ${payload.numeroVenda} finalizada.`); setCarrinho([]); setClienteId(''); setDesconto('0'); setObservacao(''); await carregar() } catch (error) { setErro(error instanceof Error ? error.message : 'Erro ao finalizar venda.') } finally { setSalvando(false) } }
  async function cancelar(venda: Venda) { const motivo = window.prompt('Motivo obrigatório do cancelamento:'); if (!motivo) return; setSalvando(true); try { const response = await adminFetch('/api/admin/vendas', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: venda.id, motivo }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? 'Erro ao cancelar venda.'); setMensagem('Venda cancelada e estoque devolvido.'); await carregar() } catch (error) { setErro(error instanceof Error ? error.message : 'Erro ao cancelar venda.') } finally { setSalvando(false) } }
  function imprimir(venda: Venda) { const itens = itensVenda.filter((i) => i.venda_id === venda.id); const cliente = relacao(venda.clientes); const janela = window.open('', '_blank', 'width=720,height=760'); if (!janela) return; janela.document.write(`<html><head><title>${esc(venda.numero_venda)}</title><style>body{font-family:Arial;padding:28px;color:#0f172a}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.totais{margin-top:18px;text-align:right;font-size:16px}.total{font-size:22px;font-weight:800}.rodape{margin-top:36px;text-align:center;color:#64748b;font-size:12px}</style></head><body><h1>Comprovante de venda</h1><p><b>${esc(venda.numero_venda)}</b> • ${dataHora(venda.criado_em)}</p><p>Cliente: ${esc(cliente?.nome ?? 'Consumidor')}</p><table><thead><tr><th>Produto</th><th>Qtd.</th><th>Unit.</th><th>Total</th></tr></thead><tbody>${itens.map((i) => `<tr><td>${esc(i.descricao)}</td><td>${numero(i.quantidade)}</td><td>${moeda(numero(i.valor_unitario))}</td><td>${moeda(numero(i.total_item))}</td></tr>`).join('')}</tbody></table><div class="totais"><p>Subtotal: ${moeda(numero(venda.subtotal))}</p><p>Desconto: ${moeda(numero(venda.desconto))}</p><p class="total">Total: ${moeda(numero(venda.total))}</p><p>Forma: ${esc(venda.forma_recebimento)}</p></div><div class="rodape">Chame o Técnico • www.chameotecnico.com.br</div><script>window.onload=()=>window.print()</script></body></html>`); janela.document.close() }

  return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-[1600px] space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black text-slate-950">Vendas</h1><p className="text-sm text-slate-500">Balcão de peças e produtos • Matriz</p></div><button type="button" onClick={adicionarAvulso} className="rounded-lg border border-orange-500 bg-white px-4 py-2.5 text-sm font-black text-orange-600 transition hover:bg-orange-50">+ Item avulso</button></header>{estruturaPendente && <div className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">Execute o arquivo supabase-add-vendas.sql no Supabase.</div>}{erro && <div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{erro}</div>}{mensagem && <div className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{mensagem}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><section className="rounded-xl bg-white p-4 shadow-sm"><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar por código, peça, categoria ou marca..." className="input" /><div className="mt-4 grid max-h-[650px] gap-3 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{loading ? <p>Carregando...</p> : filtradas.map((p) => <button key={p.id} onClick={() => adicionar(p)} className="rounded-xl border border-slate-200 p-4 text-left transition hover:border-orange-400 hover:bg-orange-50"><p className="text-xs font-bold text-slate-500">{p.codigo || 'SEM CÓDIGO'}</p><p className="mt-1 font-black text-slate-950">{p.descricao}</p><div className="mt-3 flex justify-between"><span className="font-black text-orange-600">{moeda(Number(p.valor_venda ?? 0))}</span><span className="text-xs font-bold text-slate-500">Estoque {Number(p.estoque)}</span></div></button>)}</div></section>
  <section className="rounded-xl bg-white p-4 shadow-sm"><h2 className="text-lg font-black">Carrinho</h2><div className="mt-3 max-h-[360px] space-y-2 overflow-y-auto">{carrinho.length === 0 ? <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Nenhum produto adicionado.</p> : carrinho.map((i) => <div key={i.peca.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between gap-3"><p className="font-bold">{i.peca.descricao}</p><button onClick={() => remover(i.peca.id)} className="text-xs font-black text-red-600">Remover</button></div><div className="mt-2 grid grid-cols-3 gap-2"><Campo label="Qtd."><input type="number" min="0.001" step="0.001" max={Number(i.peca.estoque)} value={i.quantidade} onChange={(e) => atualizar(i.peca.id, 'quantidade', Number(e.target.value))} className="input" /></Campo><Campo label="Valor unit."><input type="number" min="0" step="0.01" value={i.valorUnitario} onChange={(e) => atualizar(i.peca.id, 'valorUnitario', Number(e.target.value))} className="input" /></Campo><Campo label="Desconto"><input type="number" min="0" step="0.01" value={i.desconto} onChange={(e) => atualizar(i.peca.id, 'desconto', Number(e.target.value))} className="input" /></Campo></div></div>)}</div><div className="mt-4 space-y-3 border-t pt-4"><Campo label="Cliente (opcional)"><select value={clienteId} onChange={(e) => setClienteId(e.target.value)} className="input"><option value="">Consumidor não identificado</option>{clientes.map((c) => <option key={c.id} value={c.id}>{c.nome} • {c.cpf_cnpj ?? c.whatsapp ?? ''}</option>)}</select></Campo><div className="grid grid-cols-2 gap-3"><Campo label="Forma de recebimento"><select value={forma} onChange={(e) => setForma(e.target.value)} className="input"><option>PIX</option><option>CARTAO</option><option>DINHEIRO</option><option>BOLETO</option><option>DEPOSITO</option></select></Campo><Campo label="Desconto da venda"><input type="number" min="0" step="0.01" value={desconto} onChange={(e) => setDesconto(e.target.value)} className="input" /></Campo></div><Campo label="Observação"><input value={observacao} onChange={(e) => setObservacao(e.target.value)} className="input" /></Campo><div className="rounded-xl bg-slate-950 p-4 text-white"><div className="flex justify-between text-sm"><span>Subtotal</span><b>{moeda(subtotal)}</b></div><div className="mt-2 flex justify-between text-2xl"><span>Total</span><b>{moeda(total)}</b></div></div><button disabled={salvando || !carrinho.length || estruturaPendente} onClick={() => void finalizar()} className="w-full rounded-lg bg-orange-500 px-4 py-3 font-black text-white disabled:opacity-50">Finalizar venda</button></div></section></div>
  <section className="rounded-xl bg-white p-4 shadow-sm"><h2 className="mb-3 text-lg font-black">Vendas recentes</h2><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="p-3">Venda</th><th className="p-3">Cliente</th><th className="p-3">Data</th><th className="p-3">Forma</th><th className="p-3">Total</th><th className="p-3">Status</th><th className="p-3">Usuário</th><th className="p-3">Ações</th></tr></thead><tbody>{vendas.map((v) => <tr key={v.id} className="border-t"><td className="p-3 font-black">{v.numero_venda}</td><td className="p-3">{relacao(v.clientes)?.nome ?? 'Consumidor'}</td><td className="p-3">{dataHora(v.criado_em)}</td><td className="p-3">{v.forma_recebimento}</td><td className="p-3 font-black">{moeda(numero(v.total))}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-black ${v.status === 'CANCELADA' ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700'}`}>{v.status}</span></td><td className="p-3 text-xs">{v.criado_por_nome}</td><td className="p-3"><div className="flex gap-2"><button onClick={() => imprimir(v)} className="rounded border border-slate-300 px-3 py-1.5 text-xs font-black">Comprovante</button>{v.status !== 'CANCELADA' && <button disabled={salvando} onClick={() => void cancelar(v)} className="rounded bg-red-600 px-3 py-1.5 text-xs font-black text-white">Cancelar</button>}</div></td></tr>)}</tbody></table></div></section>
  </div><style jsx>{`.input{height:42px;width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:0 11px;font-size:14px}`}</style></main>
}
function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-black text-slate-600">{label}<div className="mt-1">{children}</div></label> }
function relacao<T>(value?: T | T[] | null) { return Array.isArray(value) ? value[0] : value }
function numero(value: unknown) { return Number(value ?? 0) || 0 }
function moeda(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value) }
function dataHora(value: string) { return new Date(value).toLocaleString('pt-BR') }
function esc(value: unknown) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c] ?? c) }
